name: build
on:
  push:
    tags:
      - "v*.*.*-*"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        target_name:
          - windows-cpu
          - windows-gpu
          - windows-cuda
          - linux-cuda
          - linux-cpu
        include:
          - target_name: windows-gpu
            target_device: gpu
            package_name: eb-example
            os: windows-latest
          - target_name: windows-cpu
            target_device: cpu
            package_name: eb-example-cpu
            os: windows-latest
          - target_name: windows-cuda
            target_device: cuda
            package_name: eb-example-cuda
            os: windows-latest
          - target_name: linux-cuda
            target_device: cuda
            package_name: eb-example
            os: ubuntu-latest
          - target_name: linux-cpu
            target_device: cpu
            package_name: eb-example-cpu
            os: ubuntu-latest
    steps:
      - run: "[ ${TAG_NAME#v*.*.*-} == ${{matrix.target_device}} ]"
        shell: bash
        env:
          TAG_NAME: ${{github.ref_name}}
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix code
        shell: bash
        run: |
          sed "s/\"name\": \"eb-example\",/\"name\": \"${{matrix.package_name}}\",/" package.json > package.json.tmp
          mv package.json.tmp package.json
          sed "s/\"version\": \"0.0.6\",/\"version\": \"0.0.6-${{matrix.target_device}}\",/" package.json > package.json.tmp
          mv package.json.tmp package.json
          sed "s/const targetDevice = \"cpu\";/const targetDevice = \"${{matrix.target_device}}\";/" main.js > main.js.tmp
          mv main.js.tmp main.js

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Electron
        run: npm run build
        env:
          TARGET_DEVICE: ${{matrix.target_device}}

      - name: Release Windows
        if: startsWith(matrix.os, 'windows')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/nsis-web/*
            dist/*.zip
          prerelease: true

      - name: Release Linux
        if: startsWith(matrix.os, 'ubuntu')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.AppImage
            dist/*.tar.gz
            dist/*-linux.yml
          prerelease: true
